import  { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import CustomCursor from "@/components/layout/CustomCursor";
import Navbar from "@/components/layout/Navbar";
import MobileNav from "@/components/layout/MobileNav";
import Preloader from "@/components/layout/Preloader";
import Footer from "@/components/layout/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bytewise Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/custom-animate.css" />
        <link rel="stylesheet" href="/assets/css/swiper.min.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome-all.css" />
        <link rel="stylesheet" href="/assets/css/jarallax.css" />
        <link rel="stylesheet" href="/assets/css/jquery.magnific-popup.css" />
        <link rel="stylesheet" href="/assets/css/odometer.min.css" />
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
        <link rel="stylesheet" href="/assets/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/assets/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/assets/css/nice-select.css" />
        <link rel="stylesheet" href="/assets/css/jquery-ui.css" />
        <link rel="stylesheet" href="/assets/css/twentytwenty.css" />
        <link rel="stylesheet" href="/assets/css/aos.css" />
        <link rel="stylesheet" href="/assets/css/module-css/slider.css" />
        <link rel="stylesheet" href="/assets/css/module-css/footer.css" />
        <link rel="stylesheet" href="/assets/css/module-css/banner.css" />
        <link rel="stylesheet" href="/assets/css/module-css/about.css" />
        <link rel="stylesheet" href="/assets/css/module-css/services.css" />
        <link rel="stylesheet" href="/assets/css/module-css/why-choose.css" />
        <link rel="stylesheet" href="/assets/css/module-css/process.css" />
        <link rel="stylesheet" href="/assets/css/module-css/sliding-text.css" />
        <link rel="stylesheet" href="/assets/css/module-css/project.css" />
        <link rel="stylesheet" href="/assets/css/module-css/counter.css" />
        <link rel="stylesheet" href="/assets/css/module-css/team.css" />
        <link rel="stylesheet" href="/assets/css/module-css/brand.css" />
        <link rel="stylesheet" href="/assets/css/module-css/testimonial.css" />
        <link rel="stylesheet" href="/assets/css/module-css/contact.css" />
        <link rel="stylesheet" href="/assets/css/module-css/pricing.css" />
        <link rel="stylesheet" href="/assets/css/module-css/faq.css" />
        <link rel="stylesheet" href="/assets/css/module-css/blog.css" />
        <link rel="stylesheet" href="/assets/css/module-css/newsletter.css" />
        <link rel="stylesheet" href="/assets/css/module-css/video.css" />
        <link rel="stylesheet" href="/assets/css/module-css/feature.css" />
        <link rel="stylesheet" href="/assets/css/module-css/page-header.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/responsive.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomCursor />
        <Preloader />
        <MobileNav />
        <Navbar />
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
        <Footer />
        {/* Core libs (load before interactive scripts) */}
        <Script
          src="/assets/js/jquery-latest.js"
          strategy="beforeInteractive"
        />
        <Script src="/assets/js/jquery-ui.js" strategy="beforeInteractive" />
        <Script
          src="/assets/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />

        {/* GSAP + plugins (required by `script.js`) */}
        <Script src="/assets/js/gsap/gsap.js" strategy="beforeInteractive" />
        <Script
          src="/assets/js/gsap/ScrollTrigger.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/gsap/SplitText.js"
          strategy="beforeInteractive"
        />

        {/* Vendor plugins - ensure jQuery is available first */}
        <Script
          src="/assets/js/jquery.appear.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/jquery.validate.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/jquery.magnific-popup.min.js"
          strategy="beforeInteractive"
        />
        {/* AOS (Animate On Scroll) - required by `script.js` */}
        <Script src="/assets/js/aos.js" strategy="beforeInteractive" />
        <Script src="/assets/js/isotope.js" strategy="beforeInteractive" />
        <Script
          src="/assets/js/owl.carousel.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/jquery.nice-select.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/assets/js/odometer.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/marquee.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/swiper.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/twentytwenty.js" strategy="beforeInteractive" />
        <Script src="/assets/js/wow.js" strategy="beforeInteractive" />

        {/* Particles lib - required by `app.js` */}
        <Script src="/assets/js/particles.js" strategy="beforeInteractive" />

        {/* Project scripts */}
        <Script src="/assets/js/script.js" strategy="afterInteractive" />
        <Script src="/assets/js/app.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
